2018-04-15 22:14:25,155 ERROR: Exception on /stats [GET] [in /Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wang/PycharmProjects/toxic/app/routes.py", line 121, in stats
    print pair['term'], pair['occurrences']
TypeError: string indices must be integers, not str
2018-04-15 22:14:58,131 ERROR: Exception on /stats [GET] [in /Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wang/PycharmProjects/toxic/app/routes.py", line 121, in stats
    print pair
TypeError: string indices must be integers, not str
2018-04-15 22:15:15,044 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 22:15:39,068 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 22:15:48,251 ERROR: Exception on /stats [GET] [in /Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wang/PycharmProjects/toxic/app/routes.py", line 122, in stats
    temp['label'] = pair['term'].encode('ascii', 'ignore')
TypeError: string indices must be integers, not str
2018-04-15 22:16:12,926 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 22:16:24,161 ERROR: Exception on /stats [GET] [in /Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wang/PycharmProjects/toxic/app/routes.py", line 123, in stats
    temp['label'] = pair['term'].encode('ascii', 'ignore')
TypeError: string indices must be integers, not str
2018-04-15 22:17:08,991 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 22:21:27,727 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 22:24:55,641 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 22:25:30,793 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 22:29:32,260 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 22:37:46,105 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 22:39:11,331 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 22:39:43,224 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 22:45:20,954 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 22:52:35,538 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 22:54:58,929 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 23:01:04,025 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 23:01:25,340 ERROR: Exception on /stats [GET] [in /Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py:1560]
Traceback (most recent call last):
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wang/PycharmProjects/toxic/app/routes.py", line 129, in stats
    vectorizer2, feature_matrix2 = build_feature_matrix(flattened_norm_corpus, feature_type='tfidf', min_df=0.24, max_df=0.85, ngram_range=(1, 2))
  File "/Users/wang/PycharmProjects/toxic/code/utils.py", line 57, in build_feature_matrix
    feature_matrix = vectorizer.fit_transform(documents).astype(float)
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/feature_extraction/text.py", line 1381, in fit_transform
    X = super(TfidfVectorizer, self).fit_transform(raw_documents)
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/feature_extraction/text.py", line 890, in fit_transform
    max_features)
  File "/Users/wang/anaconda3/envs/python2/lib/python2.7/site-packages/sklearn/feature_extraction/text.py", line 771, in _limit_features
    raise ValueError("After pruning, no terms remain. Try a lower"
ValueError: After pruning, no terms remain. Try a lower min_df or a higher max_df.
2018-04-15 23:01:44,319 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
2018-04-15 23:02:14,258 INFO: Microblog startup [in /Users/wang/PycharmProjects/toxic/app/__init__.py:49]
